### ISSUE TITLE
Reopen a saved project

### ISSUE THREAD

**Issue by raphaelle98** [Slookeur/Atomes#15] opened 2023-03-17 15:13 UTC
Hello,

I saved my project (output.apf) and when trying to reopen it, atomes closes and there's written on the shell 'Segmentation fault (core dumped)'. 
What could be the source of this error?

Thanks a lot

**Comment by Slookeur** [comment] 2023-03-17 15:43
Hello @raphaelle98, first of all thanks for your interest in Atomes. 
I have few questions for you in order to help:

- What kind of chemical system are you working on ?
- Can you please attached of copy of this file ? 
- Also are  you using Windows or Linux ?
- Could you describe what you were doing in Atomes at the time you saved this 'apf' file,
 I do mean at the time to did write it on the hard drive ?  

Atomes is still a work in progress, I am sorry for the inconvenience.

**Comment by raphaelle98** [comment] 2023-03-17 16:45
Hi thanks for the answer! I'm working on Linux and my system is exclusively carbon atoms. I first launched atoms from the terminal and then in the "workspace" menu I did 'import atomic coordinates'. Then I did a ring statistics calculation and tried to save my project. For this I go to "workspace" menu and under the 'project' I do 'save as' command. And I save as 'name.apf'. Then If I leave atomes and try to reopen atomes and open my project, I have the described error. 
I tried again without doing the ring statistics calculation and just save my project with the atomic coordinates and I run into the same issue. Do you want me to send you my .xyz file by email? Github doesn't support this format

**Comment by Slookeur** [comment] 2023-03-19 10:03
Hello, 
I will need a little bit more information to try and reproduce what is going on: 

- Your system seems to be periodic, please provide me with the lattice parameters.
- I need to know if you are using your own cutoff values to define bond length, if yes please send me this information. 
- Also I need to details on the ring statistics, the exact parameters that you used for the calculation.
- Finally I would like a copy of the project file 'name.apf' that you created to check it out. 

Simply reply to this post it helps to keep a track of the process to solve your issue. 
My first guess so far is that the amount of data to be written after the ring stat. might be impressive, 
considering how large is your system, so maybe there is an issue with that. 
With more details from your side I will figure this out.

**Comment by Slookeur** [comment] 2023-03-20 08:49
Just made a test, and I cannot find any issue on my side, 
see the project file I successfully saved and re-opened here: 

https://ipcms-cloud.u-strasbg.fr/owncloud/s/azkherqawqyeZ4r

**Comment by Slookeur** [comment] 2023-03-27 22:22
I uploaded a new version that will likely solve your issue, 
I actually found one with the project opening, and that might have been what was going on your side. 

Please let me know if it does the trick so I can close this issue.

**Closed as completed** 2023-07-30 17:14 UTC
